version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9091:9090"
  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter
    ports:
      - 9115:9115
    command:
      - '--config.file=/etc/blackboxexporter/config.yml'
    volumes:
      - ./blackbox.yml:/etc/blackboxexporter/config.yml
    restart: always