endpoint:
  - address: asia-east2-naturalselectionlabs.cloudfunctions.net:443
    geohash: 85bnbn0p2j8p8
    name: HongKong
  - address: europe-west1-naturalselectionlabs.cloudfunctions.net:443
    geohash: u0gvph1m9bbqh
    name: Belgium
  - address: us-central1-naturalselectionlabs.cloudfunctions.net:443
    geohash: 9zmw5c8kz5tx9
    name: Lowa
  - address: us-east1-naturalselectionlabs.cloudfunctions.net:443
    geohash: djyydm129zkud
    name: SouthCarolina
  - address: us-west1-naturalselectionlabs.cloudfunctions.net:443
    geohash: 9rcf53ky2vxs5
    name: Oregon
target:
  - module: http_2xx
    url: https://rss3.io
  - module: http_2xx
    url: https://crossbell.io
  - module: http_2xx
    url: https://faucet.crossbell.io
  - module: http_2xx
    url: https://indexer.crossbell.io/v1/characters/30
  - module: http_2xx
    url: https://rpc.crossbell.io
  - module: http_2xx
    url: https://scan.crossbell.io/api?module=block&action=eth_block_number
  - module: http_2xx
    url: https://xlog.app
  - module: http_2xx
    url: https://opsync.crossbell.io/healthcheck
  - module: http_2xx
    url: https://ipfs-relay.crossbell.io/
  - module: http_2xx
    url: https://testnet.rss3.io/data/accounts/vitalik.eth/activities?limit=1&tag=social
  - module: http_2xx
    url: https://rpc.testnet.rss3.io/
  - module: http_2xx
    url: https://scan.testnet.rss3.io/api?module=block&action=eth_block_number
  - module: http_2xx
    url: https://rsshub.app