apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: blackbox-http-sd
spec:
  jobName: blackbox
  scrapeInterval: 15s
  scrapeTimeout: 15s
  httpSDConfigs:
    - url: http://blackbox-http-discovery
      refreshInterval: 15s
  metricsPath: /blackbox_exporter
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: blackbox_exporter:9115
    - sourceLabels: [__endpoint__url]
      targetLabel: __address__
    - sourceLabels: [__endpoint__name]
      targetLabel: job
    - sourceLabels: [__endpoint__geohash]
      targetLabel: geohash
    - sourceLabels: [__endpoint__latitude]
      targetLabel: latitude
    - sourceLabels: [__endpoint__longitude]
      targetLabel: longitude
