apiVersion: v1
kind: Service
metadata:
  name: blackbox-http-discovery
spec:
  selector:
    app: blackbox-http-discovery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP