apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-http-discovery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blackbox-http-discovery
  template:
    metadata:
      labels:
        app: blackbox-http-discovery
    spec:
#      serviceAccountName: httpbin
      containers:
        - image: rss3/blackbox-hd
          imagePullPolicy: IfNotPresent
          name: server
          args:
            - --config
            - /etc/blackbox-hd/config.yaml
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /healthcheck
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8000
              path: /healthcheck
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: '0.1'
              memory: 64Mi
            limits:
              cpu: '0.5'
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/blackbox-hd
              name: config
      volumes:
        - name: config
          configMap:
            name: blackbox-http-discovery