name: Build and Deploy blackbox-hd Workflow
on:
  push:
    branches:
      - main
      - ops
    tags:
      - v*
    paths-ignore:
      - "deploy/**"
jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/blackbox-hd
      context: .
      dockerfile: ./Dockerfile
    secrets: inherit
  deploy-ops:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/blackbox-hd
      tag: sha-${{ github.sha }}
      cluster: ops
      namespace: guardian
      releaseName: blackbox-http-discovery
      revision: main
      dir: deploy/ops
    secrets: inherit
